Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 30
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	sample_distance_plot
	2

rule sample_distance_plot:
    input: /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/F1_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/F2_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/G1_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/G2_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/N01_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/N02_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/NT1_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/NT2_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/PS1_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/PS2_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/V1_featureCounts.txt, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/V2_featureCounts.txt
    output: /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/figure/distance_PNG_300_lengend_dpi.png
    jobid: 15
    wildcards: results_dir=/data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount

Error in rule sample_distance_plot:
    jobid: 15
    output: /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/03_featurecount/figure/distance_PNG_300_lengend_dpi.png

RuleException:
CalledProcessError in line 161 of /data2/zhoulab/yuxinghai/hg19_jlRNAseq/snakemake/hg19_Snakefile.py:
Command ' set -euo pipefail;  Rscript /data2/zhoulab/yuxinghai/hg19_jlRNAseq/script/distance.R ' returned non-zero exit status 1
  File "/data2/zhoulab/yuxinghai/hg19_jlRNAseq/snakemake/hg19_Snakefile.py", line 161, in __rule_sample_distance_plot
  File "/data1/zhoulab/yuxinghai/.conda/envs/py35/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data2/zhoulab/yuxinghai/hg19_jlRNAseq/snakemake/.snakemake/log/2018-04-04T112146.642423.snakemake.log
